### ISSUE TITLE
Fail to add column header in manage project assets

### ISSUE THREAD

**Issue by Jiu9Shen** [UofS-Pulse-Binfo/rawphenotypes#17]
An error happened on knowpulse at directory "Home » Administration » Tripal » Extensions» Manage Projects" when I tried to add a column header to one project (Lentil Diversity Panel Biomass or LR-11 Flowering Time) . 

The webpage showed "Error: The website encountered an unexpected error. Please try again later." after I filled in blanks and submitted. 

Other two functions "ADD EXISTING COLUMN HEADER" AND "ADD USER" on this webpage work fine.

**Comment by reynoldtan** [comment]
I've check the log file on time you made several attempts to add the trait, and all errors say:

PDOException: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "dbxref_pkey" DETAIL: Key (dbxref_id)=(3386965) already exists.: INSERT INTO chado.dbxref (db_id, accession, version, description) VALUES (:db_id, :accession, :version, :description); Array ( [:db_id] => 662 [:accession] => Days till 50% of plant have one open flower (R1; days) [:version] => [:description] => ) in chado_query() (line 1538 of /var/www/portal/sites/all/modules/contrib/tripal/tripal_core/api/tripal_core.chado_query.api.inc).

I am able to add traits without errors in my dev version. I will seek @laceysanderson comments on this.

Thanks

**Comment by laceysanderson** [comment]
Fixed by above pull request :-)
