### ISSUE TITLE
Error in deleting column header in manage project assets

### ISSUE THREAD

**Issue by Jiu9Shen** [UofS-Pulse-Binfo/rawphenotypes#19]
An error happened on knowpulse at directory "Home » Administration » Tripal » Extensions» Manage Projects" when I tried to delete column headers (R7 Traits: Canopy Height (1st; cm) and R7 Traits: Canopy Height (2nd; cm)) in one project (Lentil Diversity Panel Biomass).

After I clicked delete button on webpage, a knowpuse notice showed and asked: "Are you sure to delete this column header?". It leads to an error page when I choose yes. The column headers I tried to delete still exist after several tries. However, they disappeared after several minutes without operation.

The headers I tried to delete are EXISTING COLUMN HEADERS.

**Comment by reynoldtan** [comment]
Error was caused by traits in tripal database when it should be in rawpheno_tripal db.

This issue has been fixed when I moved all traits incorrectly saved in tripal db to rawpheno_tripal db by implementing a hook_update_N # 7201.
