### ISSUE TITLE
Make rawphenotypes pages easily accessible to data collectors.

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/rawphenotypes#21]
It has been pointed out that raw phenotypes data collectors struggle to locate links when working with the module. To address this issue, add/relocate links relevant to rawphenotypes module to a section of KP where it can be easily seen or accessed.

**Comment by reynoldtan** [comment]
Mockup #1.
![rawphenotype-block](https://user-images.githubusercontent.com/15472253/31513896-f2fb77be-af4c-11e7-8a98-05104cf45e49.jpg)

Design goals: 
- make relevant links to rawphenotypes available on first fold of the site 
- add information (eg. why backup?) to help user understand parts of the module.
- laid out as a notification area with indicators to files uploaded in backup to remind data collectors to backup your file using metaphors.

@laceysanderson 
I Love the Raw Phenotypes block: concept, content and position are bang on! My only comment is that it needs to stand out a little more... I'm worried they won't notice. Perhaps outlining the whole block in navy? Maybe more? Also, not sure about the gradient/shading... looks out of place with the rest of the front page. Maybe make the icons navy as well to increase the visibility of the block? Just throwing ideas out there.

@carolyncaron 
Passive aggressive reminders, I like it!

Mockup #2 - Revised, more contrast.
![rawphenotype-block](https://user-images.githubusercontent.com/15472253/31514894-7875c82e-af50-11e7-8e56-193173ed4b8c.jpg)

**Comment by laceysanderson** [comment]
Perfect! 

It would be extra helpful if the colour of the notification icon were based on how recent a backup had been made (Green if in the last 3 days, yellow if in the last week, red otherwise).

**Comment by laceysanderson** [comment]
Fixed in above pull request.
