### ISSUE TITLE
Issue #24 - Allow user to download environment data in download.

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/rawphenotypes#25]
![image](https://user-images.githubusercontent.com/15472253/33673441-52cb0f06-da72-11e7-83d7-a4a006625f1c.png)
Add an option to include environment data. The idea would be per project + location an environment data (when available) will be achived/zipped/compressed/packaged together with the raw phenotypic data generated by this form.

![image](https://user-images.githubusercontent.com/15472253/33673495-78cf4384-da72-11e7-958f-5b7274df9566.png)
A separate tab for environment data lists all files, as well as, allow admin to add more files for a project and location. Additional information, year is requested which will become part of the filename and distinguishes environment data file from one year to another.

To implement: Update generate_file() function to fetch environment data file based on selected project + location combination and archive. To establish relationship between environment data file and project+location, a custom table containing the following fields would be necessary.

environment_data_id (serial) primary key, project_id fk, location (varchar), year (varchar), rank/sequence/version (varchar) and file_id fk. field rank/sequence/version is a series number for each file in case 2 or more environment data for a given project + location and year.

**Comment by carolyncaron** [comment]
Addressed by above pull request and merged into master.
