### ISSUE TITLE
Issue #27 - Implement a hook to search new stock names, ignore column header(s) and provide support email

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/rawphenotypes#27]
1. Allow other module to implement drupal_alter() to some variables.
- This will be used to search germplasm with tokens for particular project.
- Ignore a set of column header(s)
- Provide a support email in rawphenotypes block.

**Comment by laceysanderson** [comment]
Fixed by the referenced pull request 🎉
