### ISSUE TITLE
Summary Barchart incorrectly states "No Data"

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/rawphenotypes#29]
_I found this bug during the Tripal 3 upgrade but it is not related to the Tripal version._

Symptom: The summary barchart displayed at phenotypes/raw when a trait is chosen, says there is no data when there is. This was experienced consistently for all traits on a KP clone site but not on the production site.

**Comment by laceysanderson** [comment]
After some digging it, I noticed the issue was related to the data query in [rawpheno_function_create_json](https://github.com/UofS-Pulse-Binfo/rawphenotypes/blob/master/include/rawpheno.function.measurements.inc#L329); specifically, [when pulling out the cvterm_id for 'location'](https://github.com/UofS-Pulse-Binfo/rawphenotypes/blob/master/include/rawpheno.function.measurements.inc#L366). There are two cvterms with the name 'location' in KP and the clone was pulling out the wrong one.

**Comment by laceysanderson** [comment]
**_Accidentally committed directly to master :-( I would still like you to both look at the change though._**

**Testing:** Go to the raw phenotypes summary page and choose a chart on a site with this commit. The barchart should show up as expected. Unfortunately the bug itself is only repeatable by chance when a new clone is created since `LIMIT 1` on an unordered query depends on the order stored on disk. That's why this is not seen on the production site.

**Comment by reynoldtan** [comment]
Checked and tested summary page.
