### ISSUE TITLE
plant/plot records only inserted (not re-used)

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/rawphenotypes#3]
**Expected Behaviour:** Each unique combination of plot, germplasm, year, rep and location should have one record in the pheno_plant table.

**Current Behaviour:** There is one entry in the pheno_plant table per row/file combination.

## Example
There are two researchers working on the same field trial (the same set of plots). One is taking data for traits 1-5 and the other is taking data for traits 6-10. This data is collected in two files (one per researcher) and uploaded independently. 

**Expected**: On download the supervisor expects to have a single row for a given plot with data for traits 1-10. This means the underlying data should be attached to a single pheno_plant record.

**Current**: The download file has two rows for a given plot. The first has data for traits 1-5 with empty data for 6-10. The second has data for 6-10 with empty data for 1-5.

**Comment by laceysanderson** [comment]
If there is more then one value for a given plot/trait then on download, put a comma-separated list in the cell and warn the user.

**Comment by reynoldtan** [comment]
Fixed bug in my 02.15.2017 - Fixed issues # 3, 4 and 5 commit.

**Comment by laceysanderson** [comment]
Appears to be fixed.
