### ISSUE TITLE
Issue #31 - Page redirect, Non-MS Excel spreadsheet, Stage 2 and 3 errors.

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/rawphenotypes#31]
- Admin pages redirect to page not found in:
  1. Create a project
  2. Delete header, user and environment data file
- Similar trait not suggested in Stage 2 - Describe Trait
- Non-Microsoft Excel spreadsheet (eg. from LibreOffice) fails validation
- Extra spaces in column headers fail Stage 3 - Save Spreadsheet

**Comment by laceysanderson** [comment]
Fixed in referenced pull request or pulled out into separate issues.
