### ISSUE TITLE
WSOD of Download page

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/rawphenotypes#33]
I'm experiencing a WSOD on the download page (phenotypes/raw/download) of my Tripal2 KnowPulse clone. It appears to be related to an empty location being passed to [rawpheno_download_load_traits](https://github.com/UofS-Pulse-Binfo/rawphenotypes/blob/tripal3-fixes/include/rawpheno.function.measurements.inc#L1075) and fed directly into the SQL query. This results in the following PDO Exception:
![screen shot 2018-02-07 at 3 06 18 pm](https://user-images.githubusercontent.com/1566301/35941774-04dfcef2-0c19-11e8-900d-d48b6ebcf93a.png)

**Comment by laceysanderson** [comment]
NOTE: There's too things to fix here. First, there should always be a check that parameters exist before passing into a query. Second, why are we getting an empty location when a default should have been chosen?

**Comment by reynoldtan** [comment]
The error is in the query to search default or all locations line #85 of rawpheno.download.form.inc. The query assumed that there is only one term 'Location' in chado.stock table. To fix the issue, modify the query and ensure to use the term 'Location' that is in or of type phenotype_measurement_types controlled vocabulary.

**Comment by reynoldtan** [comment]
Checked and tested revised queries.
