### ISSUE TITLE
Warn users not to use barchart for publication

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/rawphenotypes#4]
The barchart provided on phenotypes/raw for a specific trait utilizes raw data and as such should never be used in publication. This should be made more clear to researchers by including a disclaimer on the chart.

> The following chart uses **raw data** and, as such, should never be used in publication. It is meant to give you a quick visual and to identify problems such as outliers to aid you in your analysis.

**Comment by laceysanderson** [comment]
Update after talking to Kirstin:

> The following chart uses raw data and, as such, should never be used in publication or presentation. It is meant to give you a quick visual and to identify problems such as outliers to aid you in your analysis.

**Comment by reynoldtan** [comment]
Implemented enhancement in my 12.15.2017 - Fixed issues # 3, 4 and 5 commit.

**Comment by laceysanderson** [comment]
Confirmed the wording is fixed :-)
