### ISSUE TITLE
Whitespace between words in column header --not recognized

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/rawphenotypes#41]
When a user adds space between words in the column header for any trait (essential, optional or new), the trait should still be recognized. For example, `Planting                   Date` should match `Planting Date`.  This should match for all column types throughout all stages: stage 1 validation, new trait detection and when loading the data in stage 3.

There is a partial fix for this in https://github.com/UofS-Pulse-Binfo/rawphenotypes/pull/32/commits/40c209099c850131c1be31c4393c9ea4225cd6d0#diff-b6f1b3636044514f9512c37ba5031205R938 but it is still showing errors.

**Comment by laceysanderson** [comment]
See https://github.com/UofS-Pulse-Binfo/rawphenotypes/pull/32#issuecomment-379359869 for a screenshot and example file.

**Comment by reynoldtan** [comment]
This is a duplicate issue queue of Issue #43 Whitespace between words in column header (essential, subset etc.)
