### ISSUE TITLE
Upload failing in Step3: "Germplasm doesn't exist" when it does

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/rawphenotypes#47]
When uploading a test (file: [Test-2-NoErrors.xlsx](https://github.com/UofS-Pulse-Binfo/rawphenotypes/files/1939764/Test-2-NoErrors.xlsx)):
- step1: successfully finds all germplasm giving me a beautiful green checkmark beside all germplasm exist.
- step2: no new traits
- step3: when job is run on the command-line it fails with the following output:

> 2018-04-23 13:19:14: Calling: rawpheno_load_spreadsheet(63, a:0:{}, 1548, a:4:{i:0;s:5:"Entry";i:1;s:8:"Location";i:2;s:4:"Plot";i:3;s:3:"Rep";})
> 0% complete...
> WD rawpheno: Uploading Phenoypic Data: Germplasm doesn't exist (name=Nugget; row=2)                      [error]
> CRITICAL (RAWPHENO): Uploading Phenoypic Data: Germplasm doesn't exist (name=Nugget; row=2)
> [site http://default] [TRIPAL CRITICAL] [RAWPHENO] Uploading Phenoypic Data: Germplasm doesn't exist (name=Nugget; row=2)
> WD rawpheno: [CODE 103] Failed to load phenoypic data (job 7895)                                         [error]
> CRITICAL (RAWPHENO): [CODE 103] Failed to load phenoypic data (job 7895)
> [site http://default] [TRIPAL CRITICAL] [RAWPHENO] [CODE 103] Failed to load phenoypic data (job 7895)
> Drush command terminated abnormally due to an unrecoverable error.                                       [error]

NOTE: The germplasm does exists:

> kp3_fresh=# SELECT * FROM chado.stock WHERE name~'ugget';
>  stock_id | dbxref_id | organism_id |  name  | uniquename  | description | type_id | is_obsolete 
> ----------+-----------+-------------+--------+-------------+-------------+---------+-------------
>      8110 |   1910939 |           4 | Nugget | KP:GERM8110 |             |    3683 | f
> (1 row)

**Comment by reynoldtan** [comment]
This occurs when uploading file to AGILE project and the system could not locate germplasm name specific to the project. In this example, nugget germplasm does not have nugget AGL germplasm in the system.

This happens only to stage 3 since the system requires germplasm name with token when saving data in stage 3.

**Comment by reynoldtan** [comment]
Fix: apply the same function to search germplasm name with AGL into stage 1- validate spreadsheet to validate if germplasm has a germplasm with AGL token in the system. Instruct data collector to contact administrator (support email) if this validation failed.

**Comment by laceysanderson** [comment]
Fixed by PR.
