### ISSUE TITLE
Trait summary barchart labels incorrect

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/rawphenotypes#5]
The trait barchart currently says the y-axis is the "number of germplasm" when what is actually represented is the "number of plots". Furthermore, it says the x-axis is the average which is misleading. It only averages if there is more then one measurement for a unique trait/plot combination which is highly unlikely. It should be "Average Observed Measurements per Plot".

**Comment by laceysanderson** [comment]
X-axis: Number of Experimental Units
Y-Axis: Average Observed Measurements per Experiment Unit

**Comment by reynoldtan** [comment]
Rectified x and y axes in my 12.15.2017 - Fixed issues # 3, 4 and 5 commit.

**Comment by laceysanderson** [comment]
Confirmed wording is fixed :-)
