### ISSUE TITLE
Summary page update - wrap text in location

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/rawphenotypes#68]
Location column header stores the location of a field trial. The module does not have a uniform way of encoding the value in this column and so in one project it shows only the country information and in another it shows region/city plus the country information. This issue will implement a standard format for location by wrapping text to two rows and ideally the first line should show the country and the second line to be the region/city information. For example Saskatoon, Canada

**CANADA**
Saskatoon

or Cordoba, Spain

**SPAIN**
Cordoba

**Comment by laceysanderson** [comment]
PR Merged
