### ISSUE TITLE
Gap in x axis

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/rawphenotypes#74]
![screen shot 2018-11-05 at 10 46 52 am](https://user-images.githubusercontent.com/15472253/48012728-48032400-e0e8-11e8-8a6b-c90ae6eb9528.png)

There appears to be gap along the x axis of the Trait histogram. I believe this is caused by the extra space I've added to the heatmap to accommodate multi-line location names.

**Comment by laceysanderson** [comment]
PR Merged and changes on portal
