### ISSUE TITLE
AJAX Http request error

### ISSUE THREAD

**Issue by reynoldtan** [UofS-Pulse-Binfo/rawphenotypes#80]
![Screen Shot 2020-02-28 at 3 04 19 PM (2)](https://user-images.githubusercontent.com/15472253/75587610-7246c680-5a3c-11ea-89fb-d6aafcf15b02.png)

Unsure what is causing this, but report of this error started when moving host to HTTPS.

Related Drupal community discussion:
https://www.drupal.org/node/1232416

**Comment by reynoldtan** [comment]
Look into drush_print() in rawpheno_trpdownload_generate_file() causing progress status to fail

**Comment by laceysanderson** [comment]
@reynoldtan this is likely worth fixing in Tripal 3 -what do you think?

**Comment by laceysanderson** [comment]
Ahhh! Just saw #82 saying this is already fixed <3 Looks like the issue just wasn't closed. Thanks for the fix @reynoldtan!
